name: flutter_projects
description: Flutter apps with amazing design and moderate animations
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  flutter_vector_icons: ^1.0.0
  flutter_staggered_grid_view: ^0.4.1
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.0
  http: ^0.13.4
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  flutter_bloc: ^8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
  build_runner: ^2.1.0
  

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/pets/
    - assets/img/pet accessories/
  fonts:
    - family: MDIcons
      fonts:
        - asset: assets/icons/md_icons/MdIcons.ttf
    - family: Oswald
      fonts: 
        - asset: fonts/Oswald-Regular.ttf
    - family: Abel
      fonts:
        - asset: fonts/Abel-Regular.ttf